import './globals.css'
import { Inter } from 'next/font/google'

// const inter está aplicando uma font ao body através de uma classe
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Instituto Ser Melhor',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
		children: React.ReactNode
}) {
	return (
		<html lang="pt-br">
            <body className={inter.className}>
                {children /* children está adicionando o arquivo "page.tsx" (que é a Home) desta pasta ao body do site */}
            </body>
		</html>
	)
}
